#!/usr/bin/env bash

set -euo pipefail

sed -i -e 's/\(^mirrorlist=.*$\)/#\1/' -e 's@#baseurl=http://mirror.centos.org/centos/$releasever@baseurl=http://vault.centos.org/5.11@' /etc/yum.repos.d/CentOS-Base.repo

wget -nv -N http://yum.puppetlabs.com/puppetlabs-release-el-5.noarch.rpm
yum -y install --nogpgcheck puppetlabs-release-* epel-release
rm -f puppetlabs-release-*

yum -y update
yum -y install puppet vim-enhanced kernel-devel dkms
yum -y clean all

