#!/usr/bin/env bash

set -euo pipefail

export DEBIAN_FRONTEND=noninteractive

apt-get update
apt-get -y -o DPkg::options::="--force-confdef" -o DPkg::options::="--force-confold" upgrade
apt-get -y dist-upgrade
apt-get -y install "linux-headers-$(uname -r)" build-essential puppet dkms vim curl
apt-get -y autoremove
apt-get -y clean

sed -i -e 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
