#!/usr/bin/env bash

set -euo pipefail

yum -y update
yum -y install openjdk8 python-devel python-setup-tools make makeself zip unzip tree gcc gcc-c++ docker ant openssl-devel git subversion 'xorg*'
yum groupinstall -y 'gnome desktop'
yum remove -y initial-setup initial-setup-gui
yum -y clean all

wget http://archive.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz -O /opt/apache-maven-3.5.4-bin.tar.gz
tar -xf /opt/apache-maven-3.5.4-bin.tar.gz
rm -rf /opt/apache-maven-3.5.4-bin.tar.gz
mv apache-maven-3.5.4 /opt/apache-maven
ln -fs /opt/apache-maven/bin/mvn /usr/bin/mvn

systemctl isolate graphical.target
systemctl set-default graphical.target
