#!/usr/bin/env bash

set -euo pipefail

DIR="$(cd "$(dirname "$0")" && pwd)" && cd "$DIR"

for f in Vagrantfile upgrade_os; do
  if [[ ! -f "$f" ]]; then
    printf "File %s not found. Exiting...\n" "$f" >&2
    exit 1
  fi
done

if [[ -d .vagrant ]]; then
  vagrant destroy -f
fi

rm -rf .vagrant package.box

vagrant box update
vagrant up || true
vagrant ssh -c "sudo bash -s" < upgrade_os
vagrant reload || true
vagrant ssh -c "sudo bash -s" < ../tools/upgrade_vbguest
vagrant reload

vagrant package

vagrant destroy -f
rm -rf .vagrant

