#!/usr/bin/env bash

set -euo pipefail

for dir in /opt/VBoxGuestAdditions-*; do
  if [[ -x "${dir}/uninstall.sh" ]]; then
    "${dir}/uninstall.sh"
  fi
done

wget -nv http://download.virtualbox.org/virtualbox/5.1.22/VBoxGuestAdditions_5.1.22.iso
mkdir -p /mnt/cdrom
mount -o loop,ro VBoxGuestAdditions_5.1.22.iso /mnt/cdrom
echo 'yes' | bash /mnt/cdrom/VBoxLinuxAdditions.run
umount /mnt/cdrom

rm -rf VBoxGuestAdditions* /root/VBoxGuestAdditions* /mnt/cdrom
