#!/usr/bin/env bash

set -euo pipefail

apt-get update
apt-get -y upgrade
apt-get -y dist-upgrade
apt-get -y install "linux-headers-$(uname -r)" build-essential module-assistant dkms puppet vim
apt-get -y autoremove
apt-get -y clean

systemctl disable apt-daily.timer && systemctl disable apt-daily-upgrade.timer

sed -ie 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
