#!/usr/bin/env bash

set -euo pipefail

apt-get update
apt-get -y dist-upgrade
apt-get -y install "linux-headers-$(uname -r)" build-essential module-assistant dkms puppet vim
apt-get -y autoremove
apt-get -y clean

sed -ie 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
